name: Pull to branch with build and test (production)
run-name: ${{ github.actor }} requested a pull to master

# Triggers on a pull request to master or production being ready for review
on: 
  pull_request:
    on: ready_for_review
    branches: 
      - production

jobs:
  # setup the environment (production)
  prod-publish:
    runs-on: prncher-cloudops
    environment: 'prd'
    steps:
      # Check out repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        
      # Call publish operation
      - name: 'Publish Function App'
        uses: './.github/actions/publish-function-app'
        with:
          appName: ${{ vars.AZURE_FUNCTION_APP_NAME }} 
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }} 
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
        
  # On success, accept the PR (dev)
  prod-approve-on-success:
    needs: [prod-publish]
    runs-on: windows-latest
    if: ${{ always() && needs.prod-publish.result == 'success' }}
    steps:
      - name: Merge pull request
        uses: actions/github-script@v7
        with: 
          script: |
            const result = await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            
